# app client_id , 唯一标识当前项目绑定的 app
client_id="Xi8s3m9DCgq4Nc-wTc2Go_o1IdCwWjYtrQ69f8FsRrM"
# app name
name="test-app"

[auth]
# Oauth2 流程中的两个 url
app_url = "https://www.shoplazza.com"
redirect_url = "https://shoplazza.dev/apps/default-app-home/api/auth"
# app 所需的 scope,app 安装的时候验证是否一致
scopes = "write_order,read_order"

[build]
include_config_on_deploy = true

[webhooks]
version = "2025-04"
    [[webhooks.subscriptions]]
    topics = ["app/uninstalled"]
    uri = "https://shoplazza.dev/apps/default-app-home/api/webhooks"
